### PR TITLE
Non stored creds

### PR DESCRIPTION
**Pull request by th3xer0**
Added support for non-stored credentials (i.e. input at console prompt).  Updated config to default to non-stored.  Note that these changes are built on top of my initial cleanup.  If you decide you want to merge in my changes, may want to start with my pull request for cleanup.

Also, let me know if you would rather me keep my changes on my fork or if you want me to continue opening pull requests.  For now, I am assuming you are open for collaboration.

### CODE REVIEW

**Comment by Mila432** [comment]
@th3xer0 will this have any conflicts with 2.7? 
And I think this spaces will be destroyed later or at least with new code , I am using notepad

**Comment by davidmann4** [comment]
@th3xer0 collaboration sounds nice! Where you already able to find out how to get nearby Poke Stops and how to trigger them?

Here a example which shows nearby pokemons;
https://gist.github.com/davidmann4/906f94215f8544148b8f1251b3db1318

**Comment by th3xer0** [comment]
My updated have no conflicts with Python 2.7.  I simply changed all prints to version 3 syntax, which is 100% compatible with 2.7.

In terms of the spacing, I noticed that there was a mix of spaces and tabs for indentation, so I switched it to all spaces.  If you prefer all tabs, we can switch to that, but just trying to keep it uniform throughout the project.

For spaces around operators and commas, its the same thing, I think we should either use them (var = value) or not (var=value), but we should stick to one style (maybe just my OCD).

**Comment by Mila432** [comment]
@th3xer0 can you be the refactor guy 😂 ? I am using notepad for writing so I would have to put every single space manually 😭

**Comment by th3xer0** [comment]
I can try to take on that role. However, I will admit I am not the best with the Git workflow (any pointers would help).

**Pull request closed without merging**
