### PR TITLE
Style refactor according to PEP8

### PR DESCRIPTION
**Pull request by blackms**
I just refactored the style of the code according to PEP8 directives.

### CODE REVIEW

**Comment by Mila432** [comment]
@blackms thanks for your commit but the format will be destroyed with next commits, my windows notepad only has tabs

**Comment by blackms** [comment]
@Mila432 mhhhh :) PyCharm Community Edition is the top of the python IDE if you want to try it... I would like also to refactor some code incapsulating in some classes and objects in order to have a more structure and reusable code, are u interested or i give up?

**Comment by Mila432** [comment]
@blackms this sounds good ! but without the logic part public its makes a little sense , please wait a bit !

**Comment by blackms** [comment]
@Mila432 ok... :)

**Comment by magixx** [comment]
+1 for PyCharm
I also took a stab at this as well as code cleanup into proper classes and util for the demo. When might be a good time to start doing this? I may submit the non-working example for how it could be cleaned up.

**Pull request closed without merging**
